name: sample
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  convex_bottom_bar: ^3.2.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.5
  firebase_messaging: ^14.7.15
  calendar_date_picker2: ^0.5.3
  pie_chart: ^5.4.0
  overlay_support: ^2.1.0
  flutter:
    sdk: flutter
  intl: ^0.18.1
  google_places_flutter: ^2.0.7
  carousel_slider: ^4.2.1
  url_launcher: ^6.2.4
  flutter_local_notifications: ^16.3.2
  razorpay_flutter: ^1.3.6
  dash_chat_2: ^0.0.19
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - images/
